// <auto-generated />
using System;
using KNU.PR.DbManager.Connections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KNU.PR.DbManager.Migrations
{
    [DbContext(typeof(AzureSqlDbContext))]
    [Migration("20200909104438_ModelsCreated")]
    partial class ModelsCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KNU.PR.DbManager.Models.NewsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsEntity");
                });

            modelBuilder.Entity("KNU.PR.DbManager.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("KNU.PR.DbManager.Models.TagNewsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagOccurencesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsEntityId");

                    b.HasIndex("TagId");

                    b.ToTable("TagNewsEntity");
                });

            modelBuilder.Entity("KNU.PR.DbManager.Models.TagNewsEntity", b =>
                {
                    b.HasOne("KNU.PR.DbManager.Models.NewsEntity", "NewsEntity")
                        .WithMany()
                        .HasForeignKey("NewsEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KNU.PR.DbManager.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
